### ISSUE TITLE
Silently fails to install analyzer on “old” .csproj/packages.config projects

### ISSUE THREAD

**Issue by OliaG** [dotnet/platform-compat#61]
We need to use a PowerShell script to install analyzers in the old project system.

**Comment by terrajobst** [comment]
@pjanotti 

We need to add the PowerShell script back that was in the template. I originally yanked it because I was thinking the package makes not sense to be installed into the old CSPROJ project systems. With deprecated APIs, it would make sense so we should probably fix that.

A workaround for customers today is to use `PackageReference` in the legacy project systems, but this might not work if they have existing packages that require `packages.config` behavior.

**Comment by adamtuliper** [comment]
Is there a PowerShell script for install that the community would have access to?

**Comment by OliaG** [comment]
We will add this script

**Comment by terrajobst** [comment]
@adamtuliper 

If you install the Roslyn SDK it comes with the project template for analyzers. But I don't think the script help you to work this around as it needs to be part of a NuGet package. I think the easiest workaround is using `PackageReference` in your CSPROJ.
