### ISSUE TITLE
False positive TransactionScope.Dispose() isn't supported on Linux, MacOSX, Windows

### ISSUE THREAD

**Issue by jeremymeng** [dotnet/platform-compat#76]
It must be supported on at least one :)

Runs fine on windows/linux.

**Comment by pjanotti** [comment]
@jimcarley, @dmetzgar, @qizhanMS 

Hi, could you as owners of System.Transactions help us identify the cases below where the APIs are actually throwing PNSE? I suspect that some throw PNSE depending on the state and/or value of parameters, but some may be complete false positives (i.e.: they never throw PNSE).

Thanks,

```

DocId
--
M:System.Transactions.Transaction.System#Runtime#Serialization#ISerializable#GetObjectData(System.Runtime.Serialization.SerializationInfo,System.Runtime.Serialization.StreamingContext)
M:System.Transactions.TransactionAbortedException.#ctor(System.Runtime.Serialization.SerializationInfo,System.Runtime.Serialization.StreamingContext)
M:System.Transactions.TransactionException.#ctor(System.Runtime.Serialization.SerializationInfo,System.Runtime.Serialization.StreamingContext)
M:System.Transactions.TransactionInDoubtException.#ctor(System.Runtime.Serialization.SerializationInfo,System.Runtime.Serialization.StreamingContext)
M:System.Transactions.TransactionInterop.GetDtcTransaction(System.Transactions.Transaction)
M:System.Transactions.TransactionInterop.GetExportCookie(System.Transactions.Transaction,System.Byte[])
M:System.Transactions.TransactionInterop.GetTransactionFromDtcTransaction(System.Transactions.IDtcTransaction)
M:System.Transactions.TransactionInterop.GetTransactionFromExportCookie(System.Byte[])
M:System.Transactions.TransactionInterop.GetTransactionFromTransmitterPropagationToken(System.Byte[])
M:System.Transactions.TransactionInterop.GetTransmitterPropagationToken(System.Transactions.Transaction)
M:System.Transactions.TransactionInterop.GetWhereabouts
M:System.Transactions.TransactionManager.RecoveryComplete(System.Guid)
M:System.Transactions.TransactionManager.Reenlist(System.Guid,System.Byte[],System.Transactions.IEnlistmentNotification)
M:System.Transactions.TransactionManagerCommunicationException.#ctor(System.Runtime.Serialization.SerializationInfo,System.Runtime.Serialization.StreamingContext)
M:System.Transactions.TransactionPromotionException.#ctor(System.Runtime.Serialization.SerializationInfo,System.Runtime.Serialization.StreamingContext)
M:System.Transactions.TransactionScope.Dispose
```

**Comment by jimcarley** [comment]
All of the TransactionInterop methods are related to transaction promotion and distributed transactions that are not supported, so those are valid scenarios for PNSE.

TransactionManager.RecoveryComplete and TransactionManager.Reenlist are suspicious. There may be situations where they would throw PNSE, but I need to dig deeper.

For the *Exception(SerializationInfo) constructors, my first reaction is that these are false positives. But because they are serialization related, they might throw PNSE. I need to dig into this one, too.

TransactionScope.Dispose - I really think this is a false positive. But, there is a fair amount of code in that method which makes other calls. This could be a false positive because there is a call tree that leads to something that can throw PNSE. But I don't think there is a code path from TransactionScope.Dispose that leads to throwing PNSE. l need to dig into it to be sure.

**Comment by pjanotti** [comment]
Thanks for the quick reply Jim.

These were automatically detected by our scanner that look for code throwing PNSE until a certain depth from the entry points above. The tool checks if the PNSE is in a possible code branch from the entry points. In order to help evaluate the false positives we also log the corresponding method where the PNSE is throw. These may help when digging into specific entry points. I will grab that info and add it below.

**Comment by jimcarley** [comment]
That would be very helpful. Thanks.

**Comment by pjanotti** [comment]
Sorry for the delay (preemption :smile:). The table below has all the ones in which the site of the exception is not the method itself, notice the change in namespace since some methods have the same name.

DocId | Site
--- | ---
M:System.Transactions.TransactionInterop.GetDtcTransaction(System.Transactions.Transaction) | M:System.Transactions.Distributed.DistributedTransaction.GetDtcTransaction
M:System.Transactions.TransactionInterop.GetExportCookie(System.Transactions.Transaction,System.Byte[]) | M:System.Transactions.Distributed.DistributedTransaction.GetExportCookie(System.Byte[])
M:System.Transactions.TransactionInterop.GetTransactionFromDtcTransaction(System.Transactions.IDtcTransaction) | M:System.Transactions.Distributed.DistributedTransactionManager.GetTransactionFromDtcTransaction(System.Transactions.IDtcTransaction)
M:System.Transactions.TransactionInterop.GetTransactionFromExportCookie(System.Byte[]) | M:System.Transactions.Distributed.DistributedTransactionManager.GetTransactionFromExportCookie(System.Byte[],System.Guid)
M:System.Transactions.TransactionInterop.GetTransactionFromTransmitterPropagationToken(System.Byte[]) | M:System.Transactions.Distributed.DistributedTransactionManager.GetDistributedTransactionFromTransmitterPropagationToken(System.Byte[])
M:System.Transactions.TransactionInterop.GetTransmitterPropagationToken(System.Transactions.Transaction) | M:System.Transactions.Distributed.DistributedTransaction.GetTransmitterPropagationToken
M:System.Transactions.TransactionInterop.GetWhereabouts | M:System.Transactions.Distributed.DistributedTransactionManager.GetWhereabouts
M:System.Transactions.TransactionManager.RecoveryComplete(System.Guid) | M:System.Transactions.Distributed.DistributedTransactionManager.ResourceManagerRecoveryComplete(System.Guid)
M:System.Transactions.TransactionManager.Reenlist(System.Guid,System.Byte[],System.Transactions.IEnlistmentNotification) | M:System.Transactions.Distributed.DistributedTransactionManager.ReenlistTransaction(System.Guid,System.Byte[],System.Transactions.RecoveringInternalEnlistment)
M:System.Transactions.TransactionScope.Dispose | M:System.Transactions.EnterpriseServices.ThrowNotSupported

**Comment by jimcarley** [comment]
Thanks. This saved me a lot of time.

As I said earlier, all of the TransactionInterop calls will throw PNSE. That I am sure of.

For TransactionManager.RecoveryComplete and TransactionManager.Reenlist, those code paths would only execute if you ever connected to a distributed transaction manager, but that currently won't happen. So those two are really false positives because distributed transactions are not allowed and thus you would never connect to a distributed transaction manager.

For TransactionScope.Dispose, the code path that would lead to calling into EnterpriseServices.ThrowNotSupported won't execute, so that is a false positive. That code path would only happen if the creation of the TransactionScope successfully used EnterpriseServicesInteropOption, but that is disallowed at the outset. So Dispose won't throw PNSE.

Unfortunately, I don't see the "Site" for the *Exception(SerializationInfo) issues. Do you have those?

**Comment by pjanotti** [comment]
The tool lists then as the same but actually what is going on is that they go to the base type constructor with the same signature. I am suspecting that this was something throwing PNSE at time of 2.0 but now it is not anymore. @danmosemsft may know something about the history of these PNSE related to serialization. Meanwhile I will look at the 2.0 sources to try to confirm.

**Comment by pjanotti** [comment]
Actually the serialization ones were throwing PNSE but with commit [e3f74deb999571d3f34a6b2b8011caebcf06dbfc](https://github.com/dotnet/corefx/commit/e3f74deb999571d3f34a6b2b8011caebcf06dbfc) they were fixed in master, however, they are still present on release/2.0.0. [Example](https://github.com/dotnet/corefx/blob/5439d96765d7d6f8fae02c204c518b3c87b8d537/src/System.Transactions.Local/src/System/Transactions/TransactionException.cs#L102)

**Comment by jimcarley** [comment]
Okay. That sort of explains it. Transaction serialization is not supported in core. But actually I don't think that precludes TransactionException and its derived classes from being serializable. So that commit was actually a good thing.

Bottom line - there were a few false positives in your list - TransactionScope.Dispose, TransactionManager.Reenlist, and TransactionManager.RecoveryComplete. And the *Exception ones have dropped off the list with the commit you found.
