### ISSUE TITLE
DE0006 False Positive

### ISSUE THREAD

**Issue by nnpcYvIVl** [dotnet/platform-compat#86]
Shouldn't DE0006 be considered a false positive when using IDictionaries that are built into the base classes like Exception.Data? Is there another way to iterate over this object that doesn't trigger the analyzer?

```csharp
Exception exception = new Exception();
exception.Data.Add("test", "123");
foreach (System.Collections.DictionaryEntry dictionaryentry in exception.Data)
{
    Console.WriteLine(dictionaryentry.Key + ": " + dictionaryentry.Value);
}
```

**Comment by pjanotti** [comment]
hi @nnpcYvIVl, thanks for reporting it. Technically it is not a false positive per se, but, anyway unhelpful since you can't fix and it is not from your code. 

Perhaps the rule infrastructure needs to be enriched so it can be raised if someone is creating a new instances of the types listed in DE0006. Meanwhile is the suppression working for you?

**Comment by nnpcYvIVl** [comment]
@pjanotti Suppression works great but it would be nice if DE0006 had a blacklist of CLI types that shouldn't be reported to the user (e.g. System.Exception.Data and System.Resources.ResourceSet). It would certainly improve the signal-to-noise ratio of the analyzer.

**Comment by pjanotti** [comment]
@nnpcYvIVl yes, suppression is just as a temporary workaround. Ideally we will change this rule to report if the code create new instances of these types not if the types are used.
